title: AIR Native Extension Tutorials
show_downloads: false
google_analytics:

repository: airnativeextensions/tutorials
exclude: ["_Sidebar.md, _Footer.md"]
theme: jekyll-theme-minimal

gems: 
  - jekyll-redirect-from

